pipeline {
    agent { label 'selenium'
       // docker {
      //      image 'maven:3.9.0'
      //      args '-v /root/.m2:/root/.m2'
       // }
    }

    environment {
        credential_id = credentials('a0afeebd-d3a9-4130-88a6-3ba2e57c749c')
    }

    stages {
        stage('Checkout code') {
            steps {
                sh 'cd simple-java-maven-app'
                checkout scmGit(
                    branches: [[name: '*/master']], 
                    extensions: [], 
                    userRemoteConfigs: [[
                        credentialsId: '$credential_id', 
                        url: 'https://github.com/oriafo/Devops.git']])
                sh 'pwd'
            }
        }        
        stage('Build') {
            steps {
                sh 'cd simple-java-maven-app'
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
    }
}
